### ISSUE TITLE
a11y addon interfering with component styles

### ISSUE THREAD

**Issue by thearegee** [storybooks/storybook-addon-a11y#13]
Using decorator addA11y, it seems to interfere with our component styles.

Below shows the initial render, where the Designer name is not displayed:
![image](https://user-images.githubusercontent.com/8751165/26884223-2a27a8d0-4b97-11e7-92ce-6c7e026bfa0d.png)

I couldn't upload GIF here so here is a link on imgur:
[Toggling height corrects the view to be what is expected](http://i.imgur.com/zZtAttO.gif)

Not entirely sure whats happening however, this is the view when we disable `.addDecorator(checkA11y)`
![image](https://user-images.githubusercontent.com/8751165/26884234-30be13e6-4b97-11e7-87d1-2c9f4a952a61.png)
This is the expected view.

any ideas?

**Comment by zinserjan** [comment]
I don't know if this is related to your problem, but I noticed that the a11y addon wraps all stories with a span.

I created a PR #12 for that to remove the wrapping span. If you wanna try this, simply monkey patch WrapStory.js in your node_modules folder with the compiled version (e.g. via [babeljs repl](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code=)) of [this file](https://github.com/zinserjan/storybook-addon-a11y/blob/96a820aec52ca3766f48403c8a25dbb130fb94e2/src/components/WrapStory.js).

**Comment by chrisgreg** [comment]
Just tried that, didn't seem to fix the issue @zinserjan

**Comment by ndelangen** [comment]
FYI I have merged this repo into the monorepo!

Please do not open any issues or PR's directly on this repo, but instead open them here:
https://github.com/storybooks/storybook
