### ISSUE TITLE
Need to customise aXe options

### ISSUE THREAD

**Issue by seancurtis** [storybooks/storybook-addon-a11y#4]
The a11y checks currently cause the viewport to be scrolled. There's an option to disable that check, but there's no way to configure that for the addon. Could you please expose a way to pass the aXe options through?

**Comment by jbovenschen** [comment]
This is a thing I certain want to add in the near future only currently I don't have the time to spend much time into the project.

The idea is as following, give the provided decorator function to possibility to be a higher order function which can be passed a options object, which will look as follows;
```javascript
{ 
  axe: {
    // All possible axe config. 
  },
  screenreader: false,
  colorblindness: false,
}
```
The screenreader and color blindness filters are two things I also want to add in the future.

Looks this ok, to you?

**Comment by ndelangen** [comment]
@seancurtis I'm almost done migrating this package over into the core of storybook. Would you be interested in contributing?

Adding the options described above seem to be a great start?

https://github.com/storybooks/storybook/pull/2292

**Comment by ndelangen** [comment]
FYI I have merged this repo into the monorepo!

Please do not open any issues or PR's directly on this repo, but instead open them here:
https://github.com/storybooks/storybook
