### ISSUE TITLE
graceful-fs modification permission issue

### ISSUE THREAD

**Issue by dhartford** [storybooks/storybook-addon-a11y#6]
On windows platforms, the axe-core keeps trying to change the system npm modules:

npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)

which, by default, requires Administrator privileges. Is this needed or is there another way around it?

**Comment by ndelangen** [comment]
@dhartford is this still an issue?

FYI I have merged this repo into the monorepo!

Please do not open any issues or PR's directly on this repo, but instead open them here:
https://github.com/storybooks/storybook
